name: Run Javascript Tests

on:
pull_request:
branches: 
- context-methods

jobs:
  build:

    runs-on: ubuntu-latest
     if: github.event_name == 'pull_request'

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, build, and test
      run: |
        npm i
        npm run build --if-present
        npm test
      env:
        CI: true